spring.application.name=atm
#db configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/atm_db
spring.datasource.username = postgres
spring.datasource.password = aceplus

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

server.port=9999

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html