spring.application.name=atm
#db configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/atm_db
spring.datasource.username = postgres
spring.datasource.password = aceplus

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

server.port=9997

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html


jwt.apikey =b1a2e40f7ca0b4f0322b70d63f3a8e5b4564286a9718a35645876b48d52ce2c0
spring.security.user.name=admin
spring.security.user.password=admin123
